// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6ceaKDUO_UevYEX5H7BAwjnyKuuMWMWU',
    appId: '1:988354337193:web:6b19f95eba8f62e41c0cb8',
    messagingSenderId: '988354337193',
    projectId: 'tapcounter-f0e7d',
    authDomain: 'tapcounter-f0e7d.firebaseapp.com',
    storageBucket: 'tapcounter-f0e7d.firebasestorage.app',
    measurementId: 'G-HMHZY9F0JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4cEctVbmoKZSZVlldL__4K1p7ISrR3tI',
    appId: '1:988354337193:android:17d4f26600670f691c0cb8',
    messagingSenderId: '988354337193',
    projectId: 'tapcounter-f0e7d',
    storageBucket: 'tapcounter-f0e7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW9oEU830g_EtoW3rGTsw566klhCY4XII',
    appId: '1:988354337193:ios:a37d95b7c01e44b71c0cb8',
    messagingSenderId: '988354337193',
    projectId: 'tapcounter-f0e7d',
    storageBucket: 'tapcounter-f0e7d.firebasestorage.app',
    iosClientId: '988354337193-11fpram0gvlm1pqeishb7gcnnaj0358r.apps.googleusercontent.com',
    iosBundleId: 'com.example.tapcounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW9oEU830g_EtoW3rGTsw566klhCY4XII',
    appId: '1:988354337193:ios:a37d95b7c01e44b71c0cb8',
    messagingSenderId: '988354337193',
    projectId: 'tapcounter-f0e7d',
    storageBucket: 'tapcounter-f0e7d.firebasestorage.app',
    iosClientId: '988354337193-11fpram0gvlm1pqeishb7gcnnaj0358r.apps.googleusercontent.com',
    iosBundleId: 'com.example.tapcounter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6ceaKDUO_UevYEX5H7BAwjnyKuuMWMWU',
    appId: '1:988354337193:web:5d2337bab3e8b0be1c0cb8',
    messagingSenderId: '988354337193',
    projectId: 'tapcounter-f0e7d',
    authDomain: 'tapcounter-f0e7d.firebaseapp.com',
    storageBucket: 'tapcounter-f0e7d.firebasestorage.app',
    measurementId: 'G-G8CH462QR1',
  );

}